export const ADD_DRIVER = 'ADD_DRIVER';
export const ADD_DRIVER_SUCCESS = 'ADD_DRIVER_SUCCESS';

export const GET_DRIVERS = 'GET_DRIVERS';
export const GET_DRIVERS_SUCCESS = 'GET_DRIVERS_SUCCESS';

export const UPDATE_DRIVER = 'UPDATE_DRIVER';
export const UPDATE_DRIVER_SUCCESS = 'UPDATE_DRIVER_SUCCESS';

export const GET_DRIVER = 'GET_DRIVER';
export const GET_DRIVER_SUCCESS = 'GET_DRIVER_SUCCESS';

export const DELETE_DRIVER = 'DELETE_DRIVER';
export const DELETE_DRIVER_SUCCESS = 'DELETE_DRIVER_SUCCESS';

export const SELECT_DRIVER = 'SELECT_DRIVER';

export const AUTH_USER = 'AUTH_USER';
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';
export const AUTH_USER_FAIL = 'AUTH_USER_FAIL';

export const GET_USER = 'GET_USER';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';

export const CHECK_USERNAME = 'CHECK_USERNAME';
